# Generated by Django 5.1.15 on 2026-07-13 04:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(choices=[('fa-car', 'Car'), ('fa-car-side', 'Car (Side)'), ('fa-truck', 'Truck'), ('fa-truck-pickup', 'Pickup'), ('fa-van-shuttle', 'Van / Shuttle'), ('fa-motorcycle', 'Motorcycle'), ('fa-bus', 'Bus'), ('fa-spray-can-sparkles', 'Detailing'), ('fa-soap', 'Soap / Wash'), ('fa-droplet', 'Water / Rinse'), ('fa-broom', 'Interior Clean'), ('fa-brush', 'Polish / Wax')], default='fa-car', max_length=30)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the catalog.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_categories_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'db_table': 'services_category',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_minutes', models.PositiveIntegerField(help_text='Estimated time to complete this service, in minutes.', validators=[django.core.validators.MinValueValidator(5)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10)),
                ('available_days', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_photos/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory')),
            ],
            options={
                'db_table': 'services_service',
                'ordering': ['category__display_order', 'name'],
                'indexes': [models.Index(fields=['status'], name='services_se_status_288ecc_idx')],
            },
        ),
    ]
