# Generated by Django 5.1.15 on 2026-07-17 21:11

import apps.loyalty.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_assigned_employee'),
        ('customers', '0001_initial'),
        ('payments', '0002_alter_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], default='percentage', max_length=15)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('minimum_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited total uses.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, editable=False)),
                ('max_uses_per_customer', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loyalty_coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('tier', 'Membership Tier'), ('coupon', 'Coupon')], db_index=True, max_length=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_applications', to='bookings.booking')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='loyalty.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_applications', to='customers.customer')),
            ],
            options={
                'db_table': 'loyalty_discount_application',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('minimum_points', models.PositiveIntegerField(help_text='Lifetime points required to reach this tier.')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Automatic discount applied to every booking for members of this tier.', max_digits=5)),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplies points earned per booking, e.g. 1.5 for 50% bonus points.', max_digits=4)),
                ('icon', models.CharField(default='fa-medal', max_length=30)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_tiers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loyalty_tier',
                'ordering': ['minimum_points'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('points_balance', models.PositiveIntegerField(default=0, editable=False, help_text='Currently spendable points.')),
                ('lifetime_points', models.PositiveIntegerField(default=0, editable=False, help_text='Total ever earned -- what tier is based on.')),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('referral_code', models.CharField(default=apps.loyalty.models._generate_referral_code, editable=False, max_length=20, unique=True)),
                ('referral_bonus_granted', models.BooleanField(default=False, editable=False, help_text="Whether the referrer has already been rewarded for this customer's first booking.")),
                ('last_birthday_reward_year', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_profile', to='customers.customer')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='customers.customer')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='loyalty.loyaltytier')),
            ],
            options={
                'db_table': 'loyalty_profile',
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned_booking', 'Earned (Booking)'), ('earned_referral', 'Earned (Referral Bonus)'), ('earned_birthday', 'Earned (Birthday Bonus)'), ('redeemed', 'Redeemed'), ('adjustment', 'Manual Adjustment')], db_index=True, max_length=20)),
                ('points', models.IntegerField(help_text='Always a positive magnitude for EARNED_*; positive for REDEEMED/ADJUSTMENT means deducted.')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='bookings.booking')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='loyalty.loyaltyprofile')),
            ],
            options={
                'db_table': 'loyalty_points_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit_referral', 'Credit (Referral Bonus)'), ('credit_promotional', 'Credit (Promotional)'), ('credit_manual', 'Credit (Manual)'), ('debit_payment', 'Debit (Used for Payment)')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='payments.payment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='loyalty.loyaltyprofile')),
            ],
            options={
                'db_table': 'loyalty_wallet_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
