# Generated by Django 5.1.15 on 2026-07-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('wallet', 'Loyalty Wallet')], max_length=10),
        ),
    ]
