# Generated by Django 5.1.15 on 2026-07-12 23:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('license_plate', models.CharField(db_index=True, max_length=12, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2027)])),
                ('color', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup Truck'), ('van', 'Van / Minibus'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('other', 'Other')], default='sedan', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold / Transferred'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Internal staff notes -- never shown to the customer.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who registered this vehicle, if not self-registered by the customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_registered', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customers.customer')),
            ],
            options={
                'db_table': 'vehicles_vehicle',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='vehicles_ve_status_f71f77_idx'), models.Index(fields=['make', 'model'], name='vehicles_ve_make_6615f9_idx')],
            },
        ),
    ]
