# Generated by Django 5.1.15 on 2026-07-13 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('booking_type', models.CharField(choices=[('online', 'Online Booking'), ('walk_in', 'Walk-in')], default='online', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('in_queue', 'In Queue'), ('in_progress', 'Washing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=12)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('scheduled_time', models.TimeField()),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes_at_booking', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, help_text="Customer's notes or special requests.")),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes -- never shown to the customer.')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('confirmation_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who created this booking, if a walk-in. Null for online self-bookings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'bookings_booking',
                'ordering': ['scheduled_date', 'scheduled_time'],
                'indexes': [models.Index(fields=['scheduled_date', 'status'], name='bookings_bo_schedul_75f830_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx')],
            },
        ),
    ]
