# Generated by Django 5.1.15 on 2026-07-14 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, help_text='Staff member assigned to carry out this wash.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='employees.employee'),
        ),
    ]
